# .github/workflows/reusable-review.yml
# This is the central, reusable workflow that contains the main logic.

name: AI Code Review Workflow

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
      secrets:
      GEMINI_API_KEY:
        required: false
      AZURE_OPENAI_KEY:
        required: false

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code of the Calling Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout AI Review Action Repo
        uses: actions/checkout@v4
        with:
          repository: JP-Organization-PS/ai-review-action
          path: ./ai-review-action-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AI Review Dependencies
        working-directory: ./ai-review-action-repo
        run: npm install --legacy-peer-deps
        
      - name: Run AI Code Review
        env:
          AI_MODEL: ${{ vars.AI_MODEL }}
          GEMINI_MODEL_NAME: ${{ vars.GEMINI_MODEL_NAME }}
          GEMINI_ENDPOINT_BASE: ${{ vars.GEMINI_ENDPOINT_BASE }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT: ${{ vars.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_API_VERSION: ${{ vars.AZURE_API_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: node ./ai-review-action-repo/.github/scripts/ai-review.js